.github/workflows/gh-pages.yml
There are documentation written inline with the code in syntax_tree. As Kevin suggested, it'd be great if we could have to have an rdoc site. 
Using the GH Action - [`peaceiris/actions-gh-pages` ](https://github.com/peaceiris/actions-gh-pages), generate docs using rdoc in `./rdocs` and deploy it to GH pages
This workflow seems to be working on [my fork's project page](https://mapleong.me/syntax_tree/)
=> Generate and deploy rdoc on GH pages

.github/workflows/gh-pages.yml
Exclude: 
- Gemfile
- Rakefile
- "vendor/*"
- "bin/*"
- "test/*"
We initially only talked about the vendor directory. However, I made the decision to add the rest of the directories because they didn't contain any documentation (and so was formatted poorly) and cluttered up the side bar.  
[Tested on my fork](https://mapleong.me/syntax_tree/)
=> Exclude vendor and other directories when generating rdoc

.gitignore
QoL
And it seems we're already expecting to ignore it [here](https://github.com/ruby-syntax-tree/syntax_tree/blob/main/.github/workflows/gh-pages.yml#L19).
=> Ignore the vendor/ directory

lib/syntax_tree/node.rb
Having the `location` in the `Node` would make SyntaxTree more type-checking friendly. 
When dealing with a bare `Node`, tools are generally interested in getting the node location.
For anything else the node can be cast down to a more specific type.
=> Move `location` attribute reader to base `Node` class

lib/syntax_tree/node.rb, lib/syntax_tree/visitor.rb, test/visitor_test.rb
This pattern will expand our horizons and allow us to do fun stuff with the nodes through the `SyntaxTree::Visitor` class. Right now we are using metaprogramming to create and `#send` to call our `#visit_` methods the LSP. Ideally this would be a built in feature in `syntax_tree` so others can use it as well. 
We've chosen to require the `Visitor` class in `node.rb` to make it clearer that the file requires it. Otherwise, we'd have to add it to `lib/syntax_tree.rb` in an order-dependent way, which we decided was less desirable.
Co-authored-by: Kaan Ozkan <kaan.ozkan@shopify.com>
Co-authored-by: Alexandre Terrasa <alexandre.terrasa@shopify.com>
Co-authored-by: Vinicius Stock <vinicius.stock@shopify.com>
Co-authored-by: Emily Giurleo <emily.giurleo@shopify.com>
Co-authored-by: Rafael Franca …
=> Implement visitor pattern for SyntaxTree::Node

lib/syntax_tree/visitor.rb
Since a lot of nodes can be nil in the tree, let's provide some relief to the user.
=> Allow passing `nil` to `visit`

lib/syntax_tree/visitor.rb
Useful when you want to visit an array of nodes.
=> Introduce `visit_all`

lib/syntax_tree/node.rb, test/fixtures/command.rb
We shouldn't indent Command nodes if they end in Def/Defs/DefEndless nodes.
Fixes #21
=> Method prefixes

lib/syntax_tree/node.rb
I didn't find any node class for `AssocNew` but I found one for [`Assoc`](https://github.com/ruby-syntax-tree/syntax_tree/blob/main/lib/syntax_tree/node.rb#L1435).
=> Fix documented type for BareAssocHash#assocs

lib/syntax_tree.rb, lib/syntax_tree/json_visitor.rb, lib/syntax_tree/node.rb, lib/syntax_tree/visitor.rb, test/formatting_test.rb, test/json_visitor_test.rb, test/test_helper.rb
For posterity - most of this was generated through a script and then checked. The gist of the script is below:
```ruby
#!/usr/bin/env ruby
require "bundler/setup"
require "syntax_tree"
program = SyntaxTree.parse(SyntaxTree.read(File.expand_path("../lib/syntax_tree/node.rb", __dir__)))
program => {
statements: {
body: [
*,
SyntaxTree::ModuleDeclaration[bodystmt: {
statements: {
body: [
*,
SyntaxTree::ClassDeclaration[
constant: { constant: { value: ^(ARGV.first) } },
bodystmt: { statements: { body: } }
],
*
]
}
}]
]
}
}
body => [*, SyntaxTree::Def[name: { value: "accept" }, bodystmt: { statements: { body: [SyntaxTree::Call[message: { value: visit_method_name }]] } }], *]
body => [*, SyntaxTree::Def[name: { value: "to_json"}, bodystmt: { statements: { body: [SyntaxTree::Call[receiver: …
```
=> Serialize to JSON through a visitor

lib/syntax_tree/node.rb, lib/syntax_tree/parser.rb, test/node_test.rb
Add column positions to the `Location` class and start adding that information everywhere a new location is produced. The column means the position of the character within the specific line.
=> Add column position to Location

CHANGELOG.md, lib/syntax_tree/parser.rb, test/fixtures/arg_block.rb
Fix parsing expressions like `foo.instance_exec(&T.must(block))`, where there are two `args_add_block` calls with a single `&`. Previously it was associating the `&` with the wrong block.
Fixes #45
=> Block ampersand association

lib/syntax_tree/formatter.rb, test/formatting_test.rb
Add a class level format method that accepts the source and the node we want to format.
=> Add convenient Formatter.format

lib/syntax_tree/node.rb, test/fixtures/if.rb, test/fixtures/next.rb, test/fixtures/unless.rb
This PR is the result of our pairing session. To recap, we added:
- Allowing flow control operators to skip parens when they have single args (i.e. `next(1)` -> `next 1`)
- Prevented conditionals with a single line conditional statement as it's only statement from creating a single line conditional (i.e. Dont turn:
```ruby
if foo
a ? b : c
end
```
into
```ruby
a ? b : c if foo
```
Please let me know if I missed anything. Thanks again for hanging out. it was a blast pairing with you.
=> Adding Features

lib/syntax_tree/node.rb, test/fixtures/return.rb
This PR takes care of handling `return` nodes when argument isn Array, with or without being wrapped in parens (bonus mode!).
TBH I spent more time messing with this code then actually fixing it. I dont love how it's handling `ArrayLiterals` inside `Parens` but everything else I came up with seemed like overkill or an unnecessary abstraction. I'll trust you to make the call on if this code needs to change (which I'm happy to pair on) but for now I wanted to get it working before getting it "right" (or fast)
=> Handle `return` when arg is an `Array`

lib/syntax_tree/node.rb, lib/syntax_tree/visitor/field_visitor.rb
Add `options` as a method on `SyntaxTree::RegexpLiteral`, add it to pattern matching, and describe it using the `SyntaxTree::Visitor::FieldVisitor` class.
Closes #62
=> Options on regexp

lib/syntax_tree/node.rb, test/fixtures/if.rb
fixes https://github.com/ruby-syntax-tree/syntax_tree/issues/58
=> Disallow turning a conditional into a ternary if there's a Not node without parentheses in the predicate

lib/syntax_tree/node.rb, lib/syntax_tree/parser.rb, lib/syntax_tree/visitor.rb, lib/syntax_tree/visitor/field_visitor.rb, test/node_test.rb
As I mentioned on Slack, currently we only have access to `SyntaxTree::HeredocBeg` which only gives us the opening HEREDOC delimiter. The closing delimiter is only provided as a String in `SyntaxTree::Heredoc`. Having a `SyntaxTree::HeredocEnd` node for the closing delimiter's location would be helpful. 
Then, we won't have to do the calculations ourselves and seems more consistent with the existence of `HeredocBeg`.  
I followed the way `HeredocBeg` was implemented and added tests.
=> Introduce new node `SyntaxTree::HeredocEnd`

lib/syntax_tree/cli.rb, lib/syntax_tree/language_server.rb, test/language_server_test.rb
This lets me invoke the language server with plugins registered, to ensure that formatting works the way I want it to in my project. Rebased on top of #100 so that I could test them in concert. Works like a charm with `vscode-syntax-tree`!
P.S. this PR could stand to have a test added to make sure LSP always parses opts. LMK if the approach is sound and I'll whip up a test.
=> Allow CLI flags for lsp

lib/syntax_tree/language_server.rb, test/language_server_test.rb
While evaluating the `ruby-syntax-tree` extension I found that restarting the language server doesn't work: the JSON RPC call never resolves in the language-server client code, therefore the `await` never gets fulfilled.
Inspection of VS Code's JSON RPC stack revealed that _every_ RPC expects a response. So, I added a response to stree's LSP and verified this makes VS Code happy. With this fix in place, the restart command works!
=> Respond to LSP Shutdown command to prevent VS Code deadlocks

lib/syntax_tree/language_server.rb, lib/syntax_tree/language_server/inlay_hints.rb, test/language_server/inlay_hints_test.rb
Closes #103.
I'm retaining the support for the old-style RPC for now to avoid breaking the VS Code extension. I guess we'd technically increment the minor version of `syntax_tree`, release a new cut of the extension, and then increment the `major` version of `syntax_tree` when removing support for the proprietary stuff! What a pain.
It begs the question: should the LSP server be built into the `syntax_tree` gem, if it's likely to change frequently? I suppose that depends on the future of the parsing and formatting functions -- if some or all of the gem will be accepted as a built-in gem, then perhaps that would be a good time to split it up.
=> Add inlay hint support per LSP specification.

README.md, lib/syntax_tree.rb, lib/syntax_tree/cli.rb, test/cli_test.rb
=> Allow specifying --print-width in the CLI

lib/syntax_tree/node.rb, test/fixtures/command_call.rb
=> Deal better with multi-statement blocks inside parenthesized method calls

README.md, lib/syntax_tree/rake/check_task.rb, lib/syntax_tree/rake/write_task.rb
These rake task helpers are super handy, but they don't allow configuring the `--print-width` option.  This adds the option to both `WriteTask` and `CheckTask`, making it available in just the same way as the other options.
The existing tests for this rake task don't exercise most of the other options, so I didn't add any new tests here, especially since the logic is minimal. I have tested this locally, and it's working exactly as expected. I'm also happy to add more automated tests if you'd like.
=> Add print_width config option for rake tasks

README.md, lib/syntax_tree/cli.rb, test/cli_test.rb
Following on from conversation in #124, I'm taking a pass at what I think is a useful but fairly simple approach to supporting a config file. I'd love to hear any and all feedback on this.  I see this as a viable solution in particular but also as a means to have more concrete discussions about the topic generally.
As syntax_tree gains wider usage, it'll be very helpful to allow projects to commit their particular configs within their repo for use by any tool that uses `stree` instead of having to create wrapper scripts, rely on rake tasks that come with their own overhead, or manually keep settings up to date among all contributors.
This set of changes takes inspiration from [Sorbet](https://sorbet.org/docs/cli#config-file) to provide users with a simple config file that's also easy to …
=> Add support for a simple config file

lib/syntax_tree/language_server.rb
Partial fix for https://github.com/ruby-syntax-tree/vscode-syntax-tree/issues/45
=> switch between ruby and haml formatters

lib/syntax_tree.rb, lib/syntax_tree/language_server.rb, lib/syntax_tree/parser.rb, test/parser_test.rb
Co-authored by @devonpmack
Closes #129
=> Better error messages on missing tokens

README.md
Official support for syntax tree in Neovim via the native LSP client (https://github.com/neovim/nvim-lspconfig/pull/2056) and Vim via the ALE plugin (https://github.com/dense-analysis/ale/pull/4268) has been added. We've been using them quite successfully for a few weeks.
If anyone needs help configuring, please feel free to ping me in a discussion thread.
=> docs: add information on neovim and vim editor support

lib/syntax_tree/parser.rb, test/fixtures/def_endless.rb
Not consuming the end tokens for begins that include ensure/rescue will cause parsing endless method definitions immediately after to fail.
=> Consume end tokens on begins with rescue or ensure

lib/syntax_tree/formatter.rb
When you're formatting an individual node, it's useful to push it
onto the parent stack to make sure every child node can format
properly.
=> Use q.format for Formatter.format

lib/syntax_tree/cli.rb, test/cli_test.rb
I've been finding it too cumbersome to keep passing one-off scripts via stdin. Seen as almost all similar Ruby tooling (`ruby`, `ruby-parse`, `sorbet` are a few examples) support passing inline scripts via an `-e` option, I figured that would be a good addition to this tool as well.
I implemented the option additively, so that passing in multiple `-e` options will pass in multiple scripts. Also, in contrast to how Ruby processes `-e`, I've chosen to process all files **and** scripts passed via the command-line.
=> Add ability to pass scripts via a command line option

lib/syntax_tree/cli.rb, test/cli_test.rb
Previously, we were checking if $stdin was a TTY to determine if there was content to be read. As it turns out, this isn't really a good indicator, as content could always come later, and some folks run stree in CI when $stdin is not a TTY and still pass filenames.
Instead, we now check if no filenames were passed, and in that case we attempt to read from $stdin.
Fixes #159
=> Fix CLI checking for content

lib/syntax_tree/node.rb, lib/syntax_tree/parser.rb, test/fixtures/elsif.rb, test/fixtures/for.rb, test/fixtures/if.rb, test/fixtures/lambda.rb, test/fixtures/unless.rb, test/fixtures/until.rb, test/fixtures/while.rb
=> Fix inline comments on loop and conditional predicates

lib/syntax_tree/cli.rb
I have tested this by running it locally, but I have not written a test.
Unfortunately, I do not have further time to spend to write tests for this, if you'd like them. If this change requires tests, feel free to either push a test to this branch on my behalf or close the PR, at your discretion.
=> Allow passing `--ignore-files` multiple times

README.md, lib/syntax_tree.rb, lib/syntax_tree/visitor/environment.rb, lib/syntax_tree/visitor/with_environment.rb, test/visitor_with_environment_test.rb
Add a mixin to automatically keep track of local variables and arguments defined in the current environment for visitors. This module is very useful when trying to determine all occurrences of a particular local or its type, given a specific scope in the code.
The implementation has two parts: the `Environment` and the `WithEnvironment` module.
- The `Environment` class keeps track of what locals exist in a given environment. It also keeps a reference to an optional parent environment, since we need to go up the chain to determine whether a local is defined or not
- The `WithEnvironment` module can be included in classes inheriting from `Visitor` to override some visits methods and automatically keep track of variables
Example usage
```ruby
class MyVisitor < SyntaxTree::Visitor
include …
```
=> Add WithEnvironment mixin for visitors

lib/syntax_tree/visitor/with_environment.rb, test/visitor_with_environment_test.rb
This PR fixes a mistake made in #157
All of the visits inside the `WithEnvironment` module should use the `current_environment` method instead of accessing the instance variable directly. Otherwise, the "global" environment is not instantiated. See the included test for reproduction.
=> Fix current_environment usages to use accessor instead of instance variable

lib/syntax_tree/visitor/with_environment.rb, test/visitor_with_environment_test.rb
I found a few issues in the implementation related to aref_field, method_add_block and nested arguments.
This boils down to a var_ref, so we were actually counting them twice. Also, `visit_aref_field` would be unnecessarily complicated if the collection was a `Call`, which would need special treatment. Simply removing that visit makes it so that we only go through var_refs once and works when the collection is a `Call`
These nodes have two parts: the call and the block. Only the block requires a fresh environment block, the call occurs in the same environment that the node is found. E.g.:
```ruby
object = MyObject.new
object["attributes"].find do |a|
a["field"] == "expected"
end
```
We weren't handling the case where required positional arguments were "nested". E.g.:
```ruby
[].each do …
```
=> Fix other environment cases

test/cli_test.rb
* StringIO is thread-safe now so this test should pass reliably.
=> Unskip test_multiple_inline_scripts on TruffleRuby

lib/syntax_tree.rb, lib/syntax_tree/cli.rb
Fixes https://github.com/ruby-syntax-tree/syntax_tree/issues/196
=> Fix plugins parsing for 5.0.0

.rubocop.yml, lib/syntax_tree.rb, lib/syntax_tree/visitor/compiler.rb, test/compiler_test.rb
This commit is an experiment in transforming Syntax Tree nodes into their
corresponding YARV instruction sequences. It attempts to mirror the
behavior of `RubyVM::InstructionSequence.compile`.
You use this as with any other visitor. First you parse code into a tree,
then you visit it with this compiler. Visiting the root node of the tree
will return a `SyntaxTree::Visitor::Compiler::InstructionSequence` object.
With that object you can call `#to_a` on it, which will return a serialized
form of the instruction sequence as an array. This array _should_ mirror
the array given by `RubyVM::InstructionSequence#to_a`.
As an example, here is how you would compile a single expression:
```ruby
program = SyntaxTree.parse("1 + 2")
program.accept(SyntaxTree::Visitor::Compiler.new).to_a
[ …
```
=> EXPERIMENT: Compile to YARV instruction sequences

lib/syntax_tree/parser.rb, test/node_test.rb
We were previously relying on #bind to set up the bounds for bodystmt but that isn't sufficient. This PR fixes that. Fixes #229.
=> BodyStmt location

lib/syntax_tree/language_server.rb
My editor is sending textDocument/documentColor request to language servers. syntax_tree however raise ArgumentError when received the `textDocument/documentColor`.
Not sure if you are okay for adding but ignore `textDocument/documentColor` in syntax_tree.
=> Add and ignore textDocument/documentColor

Gemfile.lock, lib/syntax_tree.rb, lib/syntax_tree/formatter.rb, syntax_tree.gemspec, test/formatting_test.rb
Being able to override the base level of indentation allows us to format parts of a document that may be nested. This will allow the Ruby LSP to implement range formatting.
For example,
```ruby
class Foo
def bar # if we select only the bar method definition for formatting, we need to start from indentation level 2
puts "Hello"
end
end
```
The necessary changes in prettier print are here https://github.com/ruby-syntax-tree/prettier_print/pull/4.
Currently, the implementation adds the new base indentation to the last new line of the formatted source. For example,
```ruby
def foo
puts "level 2"
end
```
I'm not sure if this is coming from Syntax Tree or prettier print. This is why we currently have the `rstrip` in the tests.
=> Allow formatting code with a different base level of indentation

lib/syntax_tree/node.rb, test/fixtures/arg_paren.rb
Note that this explicitly leaves parentheses in place even if they are empty. There are two reasons we would need to do this. The first is if we're calling something that looks like a constant, as in:
Foo()
In this case if we remove the parentheses then this becomes a constant reference and not a method call. The second is if we're calling a method that is the same name as a local variable that is in scope, as in:
foo = foo()
In this case we have to keep the parentheses or else it treats this like assigning nil to the local variable. Note that we could attempt to be smarter about this by tracking the local variables that are in scope, but for now it's simpler and more efficient to just leave the parentheses in place.
Fixes #238
=> Leave parentheses in place on method calls

lib/syntax_tree/cli.rb
Previously the CLI would call `File.write` for every file, even if the contents was unchanged. This unnecessary filesystem churn can have a knock-on effect on other tools which may be watching directories for changes (e.g. IDEs). This commit updates the `stree write` command so that it only performs a write when the file contents has changed.
There is also a very slight performance improvement in the 'happy path' when files are already formatted. Measuring runtime on Discourse's core codebase (4.3k ruby files), when all files are already formatted:
| | run 1 | run 2 | run 3 | mean |
|--|--|--|--|--|
|Before| 26.4 | 27.1 | 26.1 | **26.5s** |
|After | 24.3 | 23.8 | 24.4 | **24.2s** |
Presumably this difference would be larger in environments with slower filesystems.
=> Only write files when content changes

CHANGELOG.md, lib/syntax_tree/node.rb, test/node_test.rb
Add an `arity` method to `DefNode` and `BlockNode` through `Params`. The method returns a range where the lower bound is minimum and the upper bound is the maximum number of arguments that may be used to invoke that block/method.
Question: should we add the same to `Lambda`? We have no immediate use case for it, but maybe it makes sense for completion sake.
=> Add arity to Params, DefNode and BlockNode

CHANGELOG.md, lib/syntax_tree/node.rb, test/node_test.rb
This PR's branch is based on #256.
Add arity to method invocation nodes.
=> Add arity to invocations

lib/syntax_tree/node.rb, test/fixtures/call.rb, test/fixtures/def.rb, test/fixtures/symbols.rb
They can be in a lot of places...
Fixes #274
=> EmbDoc fixes

lib/syntax_tree.rb, lib/syntax_tree/yarv/control_flow_graph.rb, lib/syntax_tree/yarv/data_flow_graph.rb, lib/syntax_tree/yarv/instruction_sequence.rb, lib/syntax_tree/yarv/instructions.rb, lib/syntax_tree/yarv/sea_of_nodes.rb, test/yarv_test.rb
=> Sea of nodes representation

lib/syntax_tree/node.rb
=> Don't rely on parent being present

lib/syntax_tree/formatter.rb, lib/syntax_tree/node.rb, lib/syntax_tree/parser.rb, lib/syntax_tree/translation.rb, lib/syntax_tree/translation/parser.rb, lib/syntax_tree/translation/rubocop_ast.rb, test/syntax_tree_test.rb, test/translation/parser_test.rb
=> Parser location

CHANGELOG.md, lib/syntax_tree/node.rb, test/fixtures/break.rb, test/fixtures/next.rb, test/fixtures/return.rb
=> Handle keywords with bare hashes

lib/syntax_tree/reflection.rb, test/test_helper.rb
Example failure:
https://github.com/ruby-syntax-tree/syntax_tree/actions/runs/4276174338/jobs/7444068581
```
$ bundle exec rake test
Coverage report generated for Unit Tests to /home/runner/work/syntax_tree/syntax_tree/coverage. 5963 / 14181 LOC (42.05%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/home/runner/work/syntax_tree/syntax_tree/lib/syntax_tree/reflection.rb:179:in `<module:Reflection>': undefined method `statements' for nil:NilClass (NoMethodError)
from /home/runner/work/syntax_tree/syntax_tree/lib/syntax_tree/reflection.rb:7:in `<module:SyntaxTree>'
from /home/runner/work/syntax_tree/syntax_tree/lib/syntax_tree/reflection.rb:3:in `<top (required)>'
from <internal:core> core/kernel.rb:234:in `gem_original_require'
from …
```
=> Fix CI for TruffleRuby

lib/syntax_tree/parser.rb, test/parser_test.rb
Lambda locals were not taking parent lines and columns into consideration in its location.
=> Fix lambda local locations

lib/syntax_tree/with_scope.rb, test/with_scope_test.rb
Add support for lambda locals, block locals and regexp named capture groups. As a side effect, because we're now visiting `vcall`, this also fixed the usages for pinned rest variables.
=> Add support for more locals in WithScope

lib/syntax_tree/with_scope.rb, test/with_scope_test.rb
Deconstructed block parameters using splats were passing an `ArgStar` instead of an `Ident` to `add_local_definition` resulting in a `no method delete_suffix` error.
Also added more tests!
=> Fix WithScope visits for deconstructed block params

README.md
Mention format support in Emacs. 
Relevant upon merge of https://github.com/lassik/emacs-format-all-the-code/pull/222
=> List editor support for Emacs

lib/syntax_tree/node.rb, lib/syntax_tree/parser.rb
This fixes two bugs. The first is that in an `in` clause, you need to use the `then` keyword or parentheses if the pattern you are matching is an endless range.
The second is that we are associating the `then` keyword with the wrong `in` clauses because they come in in reverse order and we're deleting them from the parent clauses incorrectly.
=> Fix Ruby build on HEAD

CHANGELOG.md, lib/syntax_tree/dsl.rb, lib/syntax_tree/field_visitor.rb, lib/syntax_tree/mutation_visitor.rb, lib/syntax_tree/node.rb, lib/syntax_tree/parser.rb, lib/syntax_tree/translation/parser.rb, lib/syntax_tree/visitor.rb, lib/syntax_tree/yarv/compiler.rb, lib/syntax_tree/yarv/decompiler.rb, test/node_test.rb
Related to #278. Completed with @bitwise-aiden.
This PR eliminates the `Elsif` node and folds its functionality into `IfNode`. Now, `elsif` conditional statements will be represented with `IfNodes` that are the consequent of another `IfNode`. This eliminates an unnecessary node type from syntax tree, simplifies a lot of logic, and brings syntax tree closer to other AST representations of Ruby.
=> Combine `Elsif` node with `IfNode`

lib/syntax_tree.rb, lib/syntax_tree/database.rb
Allows doing something like this:
```ruby
require "sqlite3"
database = SyntaxTree::Database::Connection.new(SQLite3::Database.new(":memory:"))
database.prepare
Dir[File.expand_path("../lib/**/*.rb", __dir__)].each do |filepath|
database.index_file(filepath)
end
database.search("Binary[left: Binary]").each do |row|
p row
end
```
=> Experimental database API

lib/syntax_tree/dsl.rb, lib/syntax_tree/field_visitor.rb, lib/syntax_tree/mutation_visitor.rb, lib/syntax_tree/node.rb, lib/syntax_tree/parser.rb, lib/syntax_tree/pretty_print_visitor.rb, lib/syntax_tree/translation/parser.rb, lib/syntax_tree/visitor.rb, lib/syntax_tree/yarv/compiler.rb
=> Add AndNode

lib/syntax_tree/node.rb, test/fixtures/lambda.rb
Fixes #379 
Previously lambda blocks inside a Command/CommandCall were always using braces, even when multiline.
This removes the special handling of multiline lambda blocks, that was forcing curly braces when any of the parents were a `Command` or `CommandCall`.
I don't understand why that was there so I can't tell if it's somehow important, but no tests failed and it made the two added fixtures pass.
=> Always use do/end for multiline lambdas

lib/syntax_tree/node.rb, lib/syntax_tree/with_scope.rb, test/with_scope_test.rb
This was caught by one of YARP's fixtures. When you have
```ruby
def foo(a = 1, (b, c))
end
```
Then `posts` will include a `MLHSParen`, which we need to account for in `WithScope` and also in the typing annotations.
=> Fix WithScope for destructured post arguments

lib/syntax_tree/cli.rb, test/cli_test.rb
Hi,
this PR adds a new CLI option that can be used to specify what kind of content is being passed via STDIN or `-e` option.
E.g.
```
cat app/views/some_file.html.erb | stree format --plugins=erb --handler=erb
```
Some tools/editors only work with formatters that support STDIN input.
=> Format non-Ruby STDIN/script content too

README.md
When trying to figure out how to format a new Ruby project, we were choosing between `@prettier/plugin-ruby`, this project, and Rufo. 
At first, we thought this project didn't have built-in support for writing to disk at all, so we almost switched to Rufo (or prettier-ruby, despite that library's admonition to use this gem). Only when I said, "no, Kevin wouldn't ship a library like this without a `--write` facility!" did we keep scrolling and find the `write` command.
=> Mention `write` from the `format` command in README

lib/syntax_tree/node.rb, test/plugin/single_quotes_test.rb
Fixes #384.
I've fixed formatting behavior for a CHAR node `?"` and `?'` when single_quotes plugin is enabled.
=> Fix formatting for CHAR node when single_quotes plugin is enabled

lib/syntax_tree/parser.rb, test/parser_test.rb
=> Track compile errors
